api/urls.py
from django.urls import path, include

from .views import ProductoList, ProductoDetalle

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>/',ProductoDetalle.as_view(),name='producto_detalle')


]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('bases.urls','bases'),namespace='bases')),
    path('inv/',include(('inv.urls','inv'),namespace='inv')),

    path('cmp/',include(('cmp.urls','cmp'),namespace='cmp')),

    path('fac/',include(('fac.urls','fac'),namespace='fac')),

    path('api/',include(('api.urls','api'),namespace='api')),

    path('admin/', admin.site.urls),
]

fac/urls.py
from django.urls import path,include

from .views import ClienteView , ClienteNew,ClienteEdit , cliente_inactivar, FacturaView, facturas , \
                   ProductoView , borrar_detalle_factura

from .reportes import imprimir_factura_recibo

urlpatterns = [
   
    path('clientes/',ClienteView.as_view(), name= 'cliente_list'),
    path('clientes/new',ClienteNew.as_view(), name= 'cliente_new'),
    path('clientes/edit/<int:pk>',ClienteEdit.as_view(), name= 'cliente_edit'),
    path('clientes/inactivar/<int:id>',cliente_inactivar, name= 'cliente_inactivar'),

    path('facturas/',FacturaView.as_view(), name= 'factura_list'),
    path('facturas/new',facturas, name= 'factura_new'),
    path('facturas/buscar-producto',ProductoView.as_view(), name= 'factura_producto'),
    path('facturas/edit/<int:id>',facturas, name= 'factura_edit'),

    path('facturas/borrar-detalle/<int:id>',borrar_detalle_factura, name= 'factura_borrar_detalle'),

     path('facturas/imprimir/<int:id>',imprimir_factura_recibo, name= 'factura_imprimir_one'),



]

inv/urls.py
from django.urls import path

from .views import CategoriaView , CategoriaNew, CategoriaEdit , \
                SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, MarcaView , MarcaNew, \
                MarcaEdit, marca_inactivar, UMNew, UMView, UMEdit, um_inactivar , ProductoView, ProductoNew, \
                ProductoEdit, producto_inactivar, categoria_inactivar, subcategoria_inactivar
                                   



urlpatterns = [
    path('categorias/',CategoriaView.as_view(), name= 'categoria_list'),
    path('categorias/new',CategoriaNew.as_view(), name= 'categoria_new'),
    path('categorias/edit/<int:pk>',CategoriaEdit.as_view(), name= 'categoria_edit'),
    path('categorias/inactivar/<int:id>',categoria_inactivar, name= 'categoria_inactivar'),
   
    path('subcategorias/',SubCategoriaView.as_view(), name= 'subcategoria_list'),
    path('subcategorias/new',SubCategoriaNew.as_view(), name= 'subcategoria_new'),
    path('subcategorias/edit/<int:pk>',SubCategoriaEdit.as_view(), name= 'subcategoria_edit'),
    path('subcategorias/inactivar/<int:id>',subcategoria_inactivar, name= 'subcategoria_inactivar'),

    path('marcas/',MarcaView.as_view(), name= 'marca_list'),
    path('marcas/new',MarcaNew.as_view(), name= 'marca_new'),
    path('marcas/edit/<int:pk>',MarcaEdit.as_view(), name= 'marca_edit'),
    path('marcas/inactivar/<int:id>',marca_inactivar, name= 'marca_inactivar'),


    path('um/',UMView.as_view(), name= 'um_list'),
    path('um/new',UMNew.as_view(), name= 'um_new'),
    path('um/edit/<int:pk>',UMEdit.as_view(), name= 'um_edit'),
    path('um/inactivar/<int:id>',um_inactivar, name= 'um_inactivar'),
    
    path('producto/',ProductoView.as_view(), name= 'producto_list'),
    path('producto/new',ProductoNew.as_view(), name= 'producto_new'),
    path('producto/edit/<int:pk>',ProductoEdit.as_view(), name= 'producto_edit'),
    path('producto/inactivar/<int:id>',producto_inactivar, name= 'producto_inactivar'),
    
    

]

fac/models.py
from django.db import models

# Create your models here.

from bases.models import ClaseModelo, ClaseModelo2
from inv.models import Producto

#para los signals

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum

class Cliente(ClaseModelo):
    NAT = 'Natural'
    JUR = 'Juridica'
    TIPO_CLIENTE = [
        (NAT,'Natural'),
        (JUR,'Juridica')
    ]
    nombres = models.CharField(
        max_length=100
    )

    apellidos = models.CharField(
        max_length=100
    )

    celular = models.CharField(
        max_length=20,
        null=True,
        blank=True
    )

    tipo = models.CharField(
        max_length=10,
        choices = TIPO_CLIENTE,
        default = NAT
    )

    def __str__(self):
        return '{} {}'.format(self.apellidos,self.nombres)
    
    def save(self):
        self.nombres = self.nombres.upper()
        self.apellidos = self.apellidos.upper()
        super(Cliente,self).save()
    
    class Meta:
        verbose_name_plural = "Clientes"



class FacturaEnc(ClaseModelo2):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField(auto_now_add=True)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

  

    def __str__(self):
        return '{}'.format(self.id)

    def save(self):
        self.total = self.sub_total - self.descuento
        super(FacturaEnc,self).save()

    class Meta:
        verbose_name_plural = "Encabezado Facturas"
        verbose_name = "Encabezado Factura"
        permissions = [
            ('sup_caja_facturaenc','Permisos de Supervisor de Caja Encabezado')
        ]

class FacturaDet(ClaseModelo2):

    factura = models.ForeignKey(FacturaEnc, on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio_prv=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)
    

    def __str__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio_prv))
        self.total = self.sub_total - float(self.descuento)
        super(FacturaDet,self).save()

    class Meta:
        verbose_name_plural = "Detalles Facturas"
        verbose_name = "Detalle Factura"
        permissions = [
            ('sup_caja_facturadet','Permisos de Supervisor de Caja Detalle')
        ]

        

@receiver(post_save, sender=FacturaDet)
def detalle_fac_guardar(sender,instance,**kwargs):
    factura_id = instance.factura.id
    producto_id = instance.producto.id

    enc = FacturaEnc.objects.get(pk=factura_id)
    if enc:
        sub_total = FacturaDet.objects \
            .filter(factura=factura_id) \
            .aggregate(sub_total=Sum('sub_total')) \
            .get('sub_total',0.00)
        
        descuento = FacturaDet.objects \
            .filter(factura=factura_id) \
            .aggregate(descuento=Sum('descuento')) \
            .get('descuento',0.00)
        
        enc.sub_total = sub_total
        enc.descuento = descuento
        enc.save()

    prod=Producto.objects.filter(pk=producto_id).first()
    if prod:
        cantidad = int(prod.existencia) - int(instance.cantidad)
        prod.existencia = cantidad
        prod.save()

fac/forms.py
from django import forms

from .models import Cliente


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente

        fields=['nombres','apellidos','tipo',
                'celular','estado']
        
       
        exclude = ['um','fm','uc','fc']
        widget = {'descripcion':forms.TextInput}

    def __init__(self,*args, **kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

fac/views.py
from django.shortcuts import render, redirect

from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin

from  django.contrib.messages.views import SuccessMessageMixin

from django.urls import reverse_lazy

from django.contrib import messages

from .models import Cliente, FacturaEnc, FacturaDet

from .forms import ClienteForm

from django.contrib.auth.decorators import login_required, permission_required
# Create your views here.

from bases.views import SinPrivilegios

from django.http import HttpResponse
from datetime import datetime

import inv.views as inv

from inv.models import Producto

from django.contrib.auth import authenticate


class ClienteView(LoginRequiredMixin,SinPrivilegios, generic.ListView):
    permission_required = "fac.view_cliente"
    model =  Cliente
    template_name = "fac/cliente_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class VistaBaseCreate(SuccessMessageMixin,SinPrivilegios,\
      generic.CreateView):
      context_object_name = 'obj'
      success_message = "Registro Agregado Satisfactoriamente"

      def form_valid(self, form):
            form.instance.uc = self.request.user
            return super().form_valid(form)

class VistaBaseEdit(SuccessMessageMixin,SinPrivilegios,\
      generic.UpdateView):
      context_object_name = 'obj'
      success_message = "Registro Actualizado Satisfactoriamente"

      def form_valid(self, form):
            form.instance.um = self.request.user.id
            return super().form_valid(form)


class ClienteNew(LoginRequiredMixin,VistaBaseCreate):
    model=Cliente
    template_name = "fac/cliente_form.html"
    form_class = ClienteForm
    success_url = reverse_lazy("fac:cliente_list")
    permission_required = "fac.add_cliente"


class ClienteEdit(LoginRequiredMixin,VistaBaseEdit):
    model=Cliente
    template_name = "fac/cliente_form.html"
    form_class = ClienteForm
    success_url = reverse_lazy("fac:cliente_list")
    permission_required = "fac.change_cliente"


@login_required(login_url='/login/')
@permission_required('fac.change_cliente', login_url='bases:sin_privilegios')
def cliente_inactivar(request, id):
    pro = Cliente.objects.filter(pk=id).first()

    contexto = {}
    template_name = "fac/inactivar_prv.html"

    if not pro:
        return redirect("fac:cliente_list")

    if request.method=='GET':
        contexto={"obj":pro}

    if request.method=='POST':
        pro.estado=False
        pro.save()
        messages.success(request, 'Cliente Inactivado')
        return redirect('fac:cliente_list')

    return render(request,template_name,contexto)


class FacturaView(LoginRequiredMixin,SinPrivilegios,generic.ListView):
    model = FacturaEnc
    template_name= "fac/factura_list.html"
    context_object_name = "obj"
    permission_required = "fac.view_facturaenc"



@login_required(login_url='/login/')
@permission_required('fac.change_facturaenc', login_url='bases:sin_privilegios')
def facturas(request,id=None):
    template_name='fac/facturas.html'

    detalle = {}
    clientes = Cliente.objects.filter(estado=True)
    
    if request.method == "GET":
        enc = FacturaEnc.objects.filter(pk=id).first()
        if not enc:
            encabezado = {
                'id':0,
                'fecha':datetime.today(),
                'cliente':0,
                'sub_total':0.00,
                'descuento':0.00,
                'total': 0.00
            }
            detalle=None
        else:
            encabezado = {
                'id':enc.id,
                'fecha':enc.fecha,
                'cliente':enc.cliente,
                'sub_total':enc.sub_total,
                'descuento':enc.descuento,
                'total':enc.total
            }

        detalle=FacturaDet.objects.filter(factura=enc)
        contexto = {"enc":encabezado,"det":detalle,"clientes":clientes}
        return render(request,template_name,contexto)
    
    if request.method == "POST":
        cliente = request.POST.get("enc_cliente")
        fecha  = request.POST.get("fecha")
        cli=Cliente.objects.get(pk=cliente)

        if not id:
            enc = FacturaEnc(
                cliente = cli,
                fecha = fecha
            )
            if enc:
                enc.save()
                id = enc.id
        else:
            enc = FacturaEnc.objects.filter(pk=id).first()
            if enc:
                enc.cliente = cli
                enc.save()

        if not id:
            messages.error(request,'No Puedo Continuar No Pude Detectar No. de Factura')
            return redirect("fac:factura_list")
        
        codigo = request.POST.get("codigo")
        cantidad = request.POST.get("cantidad")
        precioo = request.POST.get("precio")
        s_total = request.POST.get("sub_total_detalle")
        descuento = request.POST.get("descuento_detalle")
        total = request.POST.get("total_detalle")

        prod = Producto.objects.get(codigo=codigo)
        det = FacturaDet(
            factura = enc,
            producto = prod,
            cantidad = cantidad,
            precio_prv = precioo,
            sub_total = s_total,
            descuento = descuento,
            total = total
        )
        
        if det:
            det.save()
        
        return redirect("fac:factura_edit",id=id)

    return render(request,template_name,contexto)


class ProductoView(inv.ProductoView):
    template_name="fac/buscar_producto.html" 


def borrar_detalle_factura(request, id):
    template_name = "fac/factura_borrar_detalle.html"

    det = FacturaDet.objects.get(pk=id)

    if request.method=="GET":
        context={"det":det}

    if request.method == "POST":
        usr = request.POST.get("usuario")
        pas = request.POST.get("pass")

        user =authenticate(username=usr,password=pas)

        if not user:
            return HttpResponse("Usuario o Clave Incorrecta")
        
        if not user.is_active:
            return HttpResponse("Usuario Inactivo")

        if user.is_superuser or user.has_perm("fac.sup_caja_facturadet"):
            det.id = None
            det.cantidad = (-1 * det.cantidad)
            det.sub_total = (-1 * det.sub_total)
            det.descuento = (-1 * det.descuento)
            det.total = (-1 * det.total)
            det.save()

            return HttpResponse("ok")

        return HttpResponse("Usuario no autorizado")

    return render(request,template_name,context)

fac/templates/fac/buscar_producto.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Buscar Producto
                        </div>
                        <div class="dropdown-divider"></div>
                        
                        <div class="row">
                                <table
                                id="tblProducto"
                                data-pagination="true"
                                data-search="true"
                                data-show-columns="true"
                                data-show-fullscreen="true"
                                data-locale="es-MX"
                                >
                                <thead>
                                  <th data-sortable="true" data-field="id">Id</th>        
                                  <th data-sortable="true" data-field="codigo">Código</th>
                                  <th data-sortable="true" data-field="codigo_barra">Barra</th>
                                  <th data-field="descripcion">Descripción</th>
                                  <th data-field="existencia">Existencia</th>
                                  <th data-field="precio">Precio</th>
                                  <th class="all">Acciones</th>
                                </thead>
                                <tbody>
                                  {% for item in obj%}
                                  <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.codigo }}</td>
                                    <td>{{ item.codigo_barra }}</td>
                                    <td>{{item.descripcion}}</td>
                                    <td>{{item.existencia}}</td>
                                    <td>{{item.precio}}</td>
                                    <td>
                                        {% if item.existencia > 0 and item.estado %}
                                        <button class="btn btn-warning btn-circle" id="btnSelect" 
                                        onclick="seleccionarProducto({{item.id}},'{{item.codigo}}','{{item.descripcion}}',{{item.precio}})">
                                            <i class="far fa-hand-pointer"></i>
                                        </button>
                                        {% endif %}
                                    </td>
                                  </tr>
                                  {% endfor %}
                                </tbody>
                              </table>
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <!-- <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button> -->
                                <button type="button" id="btnCancelar" class="btn btn-success">
                                        <!-- onclick="return cerrar_modal()" -->
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
{% block js_page %}
<script>
    $(function () {

        $("#btnCancelar").click(function(e){
            e.preventDefault();
            cerrar_modal();

        });
    });
    $('#tblProducto').bootstrapTable();

    function seleccionarProducto(id,codigo,descripcion,precio){
        $("#codigo").val(codigo);
        $("#descripcion").val(descripcion);
        $("#precio").val(precio);
        $("#btnCancelar").click();
        $("#codigo").select();
        $("#codigo").focus();

    }

</script>
{% endblock %}

fac/templates/fac/cliente_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline" action="">
    {% csrf_token %}

    <div class="col-xl-12 col-md-12 mb-12">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
        <div class="card border-left-success shadow h-100 py-2">
            {% endif %}

          <div class="card-body">
            <div class="row no-gutters align-items-center">
              <div class="col mr-2">
                <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                   {% if obj %} Editar {% else %} Nuevo {% endif %} Cliente
                </div>
                
              

              <div class="dropdown-divider"></div>
                <div class="row">

                   {{ form.as_p}}

               </div>

               <div class="dropdown-divider"></div>

               <div class="row">

                    <div class="col">
                        <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                        <a href="{% url 'fac:cliente_list' %}" class="btn btn-success"><span class="fa fa-undo"> Cancelar</span></a>
                    </div>
               </div>

            
            
               
            </div>
            </div>
          </div>
        </div>
      </div>  

</form>

{% endblock %}

{% block js_page %}
{% endblock %}

fac/templates/fac/cliente_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Clientes</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones:</div>
          <a class="dropdown-item" href="{% url 'fac:cliente_new' %}"><i class="fa fa-calendar-plus"></i> Nuevo</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay Clientes</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Tipo</th>
                <th>Telefono</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.nombres}}</td>
                        <td>{{item.apellidos}}</td>
                        <td>{{item.tipo}}</td>
                        <td>{{item.celular}}</td>
                        <td>{{item.estado | yesno:"Activo,Inactivo"}}</td>
                        <td>
                            <a href="{%url 'fac:cliente_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'fac:cliente_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
</script>
{% endblock %}

fac/templates/fac/factura_borrar_detalle.html
<label class="text-danger">¿Anular Producto <b>{{det.producto.descripcion}}</b> de factura <b>{{det.factura.id}}</b>?</label>
<div>
    <div class="form-group">
        <label class="control-label">Usuario</label>
        <input type="text" id="usuario" class="form-control" required>
    </div>
    <div class="form-group">
        <label class="control-label">Contraseña</label>
        <input type="password" id="password" class="form-control" required>
    </div>
</div>

fac/templates/fac/factura_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Facturas</h6>
      <!----> <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones:</div>
          <a class="dropdown-item" href="{% url 'fac:factura_new' %}"><i class="fa fa-calendar-plus"></i> Nueva</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay Facturas</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>No.</th>
                <th>Cliente</th>
                <th>Total</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.cliente}}</td>
                        <td>{{item.total}}</td>
                        <td>{{item.estado | yesno:"Activo,Inactivo"}}</td>
                        <td>
                            <a href="{% url 'fac:factura_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>        
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
 $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
</script>
{% endblock %}

fac/templates/fac/inactivar_prv.html
{% extends 'base/base.html' %}

{% block page_content %}

<form method="POST" class="form-inline">
  {% csrf_token %}
  <div class="col-xl-4 col-md-6 mb-6">
    <div class="card border-left-danger shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿Inactivar a Cliente {{ obj.nombres }}?</div>
            <button type="submit" class="btn btn-danger"><i class="far fa-question-circle"></i> Si, Inactivar</button>
            
            <!-- <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"> Cancelar</span></a> -->

            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"> Cancelar</span></a>

          </div>
          <div class="col-auto">
            <i class="far fa-question-circle fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>  

</form>

{% endblock %}

{% block js_page %}
{% endblock %}