api/urls.py
from django.urls import path, include

from .views import ProductoList, ProductoDetalle

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>/',ProductoDetalle.as_view(),name='producto_detalle')


]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('',include(('bases.urls','bases'),namespace='bases')),
    path('inv/',include(('inv.urls','inv'),namespace='inv')),

    path('cmp/',include(('cmp.urls','cmp'),namespace='cmp')),

    path('fac/',include(('fac.urls','fac'),namespace='fac')),

    path('api/',include(('api.urls','api'),namespace='api')),

    path('admin/', admin.site.urls),
]

inv/urls.py
from django.urls import path

from .views import CategoriaView , CategoriaNew, CategoriaEdit , \
                SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, MarcaView , MarcaNew, \
                MarcaEdit, marca_inactivar, UMNew, UMView, UMEdit, um_inactivar , ProductoView, ProductoNew, \
                ProductoEdit, producto_inactivar, categoria_inactivar, subcategoria_inactivar
                                   



urlpatterns = [
    path('categorias/',CategoriaView.as_view(), name= 'categoria_list'),
    path('categorias/new',CategoriaNew.as_view(), name= 'categoria_new'),
    path('categorias/edit/<int:pk>',CategoriaEdit.as_view(), name= 'categoria_edit'),
    path('categorias/inactivar/<int:id>',categoria_inactivar, name= 'categoria_inactivar'),
   
    path('subcategorias/',SubCategoriaView.as_view(), name= 'subcategoria_list'),
    path('subcategorias/new',SubCategoriaNew.as_view(), name= 'subcategoria_new'),
    path('subcategorias/edit/<int:pk>',SubCategoriaEdit.as_view(), name= 'subcategoria_edit'),
    path('subcategorias/inactivar/<int:id>',subcategoria_inactivar, name= 'subcategoria_inactivar'),

    path('marcas/',MarcaView.as_view(), name= 'marca_list'),
    path('marcas/new',MarcaNew.as_view(), name= 'marca_new'),
    path('marcas/edit/<int:pk>',MarcaEdit.as_view(), name= 'marca_edit'),
    path('marcas/inactivar/<int:id>',marca_inactivar, name= 'marca_inactivar'),


    path('um/',UMView.as_view(), name= 'um_list'),
    path('um/new',UMNew.as_view(), name= 'um_new'),
    path('um/edit/<int:pk>',UMEdit.as_view(), name= 'um_edit'),
    path('um/inactivar/<int:id>',um_inactivar, name= 'um_inactivar'),
    
    path('producto/',ProductoView.as_view(), name= 'producto_list'),
    path('producto/new',ProductoNew.as_view(), name= 'producto_new'),
    path('producto/edit/<int:pk>',ProductoEdit.as_view(), name= 'producto_edit'),
    path('producto/inactivar/<int:id>',producto_inactivar, name= 'producto_inactivar'),
    
    

]

bases/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User

from django_userforeignkey.models.fields import UserForeignKey

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract=True

class ClaseModelo2(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    # uc = models.ForeignKey(User, on_delete=models.CASCADE)
    # um = models.IntegerField(blank=True,null=True)
    uc = UserForeignKey(auto_user_add=True, related_name='+')
    um = UserForeignKey(auto_user_add=True, related_name='+')

    class Meta:
        abstract=True

inv/models.py
from django.db import models

# Create your models here.


from bases.models import ClaseModelo


class Categoria(ClaseModelo):
    descripcion = models.CharField(max_length=100,help_text='Descripcion de la categoria',
    unique=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural= "Categorias"


class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text= 'Descripcion de  la Categoria',
        
    )

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion,self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria,self).save()
    
    class Meta:
        verbose_name_plural= "Sub Categorias"
        unique_together = ('categoria','descripcion')


class Marca(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la Marca',
        unique=True
    )
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()
    
    class Meta:
        verbose_name_plural = "Marca"


class UnidadMeidida(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la Unidad Medida',
        unique=True
    )
    def __str__(self):
        return '{}'.format(self.descripcion)
    
    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadMeidida, self).save()
    
    class Meta:
        verbose_name_plural = "Unidades de Medida"

class Producto(ClaseModelo):
    codigo= models.CharField(
        max_length=100,
        unique=True
    )

    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=100)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True,blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadMeidida, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto,self).save()

    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('codigo','codigo_barra')

inv/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import generic

from django.contrib import messages

from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from .models import Categoria, SubCategoria , Marca, UnidadMeidida, Producto

from .forms import CategoriaForm, SubCategoriaForm , MarcaForm , UMForm, ProductoForm

from bases.views import SinPrivilegios

from django.contrib.messages.views import  SuccessMessageMixin

from django.contrib.auth.decorators import login_required, permission_required



class CategoriaView(LoginRequiredMixin, SinPrivilegios, generic.ListView):
    permission_required = "inv.view_categoria"
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class CategoriaNew(SuccessMessageMixin, LoginRequiredMixin,SinPrivilegios, generic.CreateView):
    permission_required = "inv.add_categoria"
    model = Categoria
    template_name= "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inv:categoria_list")
    login_url = 'bases:login'
    success_message= "Categoria Creada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class CategoriaEdit(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "inv.change_categoria"
    model = Categoria
    template_name= "inv/categoria_form.html"
    context_object_name = "obj"
    form_class = CategoriaForm
    success_url = reverse_lazy("inv:categoria_list")
    login_url = 'bases:login'
    success_message= "Categoria Actualizada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_categoria', login_url='bases:sin_privilegios')
def categoria_inactivar(request, id):
    cat = Categoria.objects.filter(pk=id).first()

    contexto = {}
    template_name = "inv/catalogos_del.html"

    if not cat:
        return redirect("inv:categoria_list")

    if request.method=='GET':
        contexto={"obj":cat}

    if request.method=='POST':
        cat.estado=False
        cat.save()
        messages.success(request,'Categoria Inactivada')
        return redirect('inv:categoria_list')

    return render(request,template_name,contexto)


class SubCategoriaView(LoginRequiredMixin, SinPrivilegios, generic.ListView):
    permission_required = "inv.view_subcategoria"
    model = SubCategoria
    template_name = "inv/subcategoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'


class SubCategoriaNew(SuccessMessageMixin, LoginRequiredMixin,SinPrivilegios, generic.CreateView):
    permission_required = "inv.add_subcategoria"
    model = SubCategoria
    template_name= "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = 'bases:login'
    success_message= "SubCategoria Creada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class SubCategoriaEdit(SuccessMessageMixin, LoginRequiredMixin,SinPrivilegios, generic.UpdateView):
    permission_required = "inv.change_subcategoria"
    model = SubCategoria
    template_name= "inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class = SubCategoriaForm
    success_url = reverse_lazy("inv:subcategoria_list")
    login_url = 'bases:login'
    success_message= "SubCategoria Actualizada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_subcategoria', login_url='bases:sin_privilegios')
def subcategoria_inactivar(request, id):
    sub = SubCategoria.objects.filter(pk=id).first()

    contexto = {}
    template_name = "inv/catalogos_del.html"

    if not sub:
        return redirect("inv:subcategoria_list")

    if request.method=='GET':
        contexto={"obj":sub}

    if request.method=='POST':
        sub.estado=False
        sub.save()
        messages.success(request,'SubCategoria Inactivada')
        return redirect('inv:subcategoria_list')

    return render(request,template_name,contexto)


class MarcaView(LoginRequiredMixin, SinPrivilegios, generic.ListView):
    permission_required = "inv.view_marca"
    model = Marca
    template_name = "inv/marca_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class MarcaNew(SuccessMessageMixin, LoginRequiredMixin,SinPrivilegios, generic.CreateView):
    permission_required = "inv.add_marca"
    model = Marca
    template_name= "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForm
    success_url = reverse_lazy("inv:marca_list")
    login_url = 'bases:login'
    success_message= "Marca Creada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class MarcaEdit(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "inv.change_marca"
    model = Marca
    template_name= "inv/marca_form.html"
    context_object_name = "obj"
    form_class = MarcaForm
    success_url = reverse_lazy("inv:marca_list")
    login_url = 'bases:login'
    success_message= "Marca Actualizada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_marca', login_url='bases:sin_privilegios')
def marca_inactivar(request, id):
    marca = Marca.objects.filter(pk=id).first()

    contexto = {}
    template_name = "inv/catalogos_del.html"

    if not marca:
        return redirect("inv:marca_list")

    if request.method=='GET':
        contexto={"obj":marca}

    if request.method=='POST':
        marca.estado=False
        marca.save()
        messages.success(request,'Marca Inactivada')
        return redirect('inv:marca_list')

    return render(request,template_name,contexto)


class UMView(LoginRequiredMixin, SinPrivilegios, generic.ListView):
    permission_required = "inv.view_unidadmeidida"
    model = UnidadMeidida
    template_name = "inv/um_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class UMNew(SuccessMessageMixin, LoginRequiredMixin,SinPrivilegios, generic.CreateView):
    permission_required = "inv.add_unidadmeidida"
    model = UnidadMeidida
    template_name= "inv/um_form.html"
    context_object_name = "obj"
    form_class = UMForm
    success_url = reverse_lazy("inv:um_list")
    login_url = 'bases:login'
    success_message= "UM Creada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        print(self.request.user.id)
        return super().form_valid(form)

class UMEdit(SuccessMessageMixin, LoginRequiredMixin,SinPrivilegios, generic.UpdateView):
    permission_required = "inv.change_unidadmeidida"
    model = UnidadMeidida
    template_name= "inv/um_form.html"
    context_object_name = "obj"
    form_class = UMForm
    success_url = reverse_lazy("inv:um_list")
    login_url = 'bases:login'
    success_message= "UM Actualizada Satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        print(self.request.user.id)
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_unidadmeidida', login_url='bases:sin_privilegios')
def um_inactivar(request, id):
    um = UnidadMeidida.objects.filter(pk=id).first()

    contexto = {}
    template_name = "inv/catalogos_del.html"

    if not um:
        return redirect("inv:um_list")

    if request.method=='GET':
        contexto={"obj":um}

    if request.method=='POST':
        um.estado=False
        um.save()
        messages.success(request,'UM Inactivada')
        return redirect('inv:um_list')

    return render(request,template_name,contexto)


class ProductoView(LoginRequiredMixin, SinPrivilegios, generic.ListView):
    permission_required = "inv.view_producto"
    model = Producto
    template_name = "inv/producto_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'


class ProductoNew(SuccessMessageMixin, LoginRequiredMixin,SinPrivilegios, generic.CreateView):
    permission_required = "inv.add_producto"
    model = Producto
    template_name= "inv/producto_form.html"
    context_object_name = "obj"
    form_class = ProductoForm
    success_url = reverse_lazy("inv:producto_list")
    login_url = 'bases:login'
    success_message= "Producto Creado Satisfactoriamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class ProductoEdit(SuccessMessageMixin, LoginRequiredMixin, SinPrivilegios, generic.UpdateView):
    permission_required = "inv.change_producto"
    model = Producto
    template_name= "inv/producto_form.html"
    context_object_name = "obj"
    form_class = ProductoForm
    success_url = reverse_lazy("inv:producto_list")
    login_url = 'bases:login'
    success_message= "Producto Actualizado Satisfactoriamente"

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

@login_required(login_url='/login/')
@permission_required('inv.change_producto', login_url='bases:sin_privilegios')
def producto_inactivar(request, id):
    prod = Producto.objects.filter(pk=id).first()

    contexto = {}
    template_name = "inv/catalogos_del.html"

inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Categorias</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:categoria_new' %}"><i class="fa fa-calendar-plus"></i> Nueva</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay categorias</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripcion</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>F. Modif</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.descripcion}}</td>
                        <td>{{item.estado | yesno:"Activo,Inactivo"}}</td>
                        <td>{{item.fc|date:"d/m/Y H:i"}}</td>
                        <td>{{item.fm|date:"d/m/Y H:i"}}</td>
                        <td>
                            <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:categoria_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  $(document).ready(function(){
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
</script>
{% endblock %}

inv/templates/inv/marca_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Marcas</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:marca_new' %}"><i class="fa fa-calendar-plus"></i> Nueva</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay Marcas</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripcion</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>F. Modif</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.descripcion}}</td>
                        <td>{{item.estado | yesno:"Activo,Inactivo"}}</td>
                        <td>{{item.fc|date:"d/m/Y H:i"}}</td>
                        <td>{{item.fm|date:"d/m/Y H:i"}}</td>
                        <td>
                            <a href="{% url 'inv:marca_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:marca_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
  $(document).ready(function(){
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
</script>
{% endblock %}

inv/templates/inv/producto_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Listado de Productos</h6>
      <div class="dropdown no-arrow">
        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
          <div class="dropdown-header">Acciones</div>
          <a class="dropdown-item" href="{% url 'inv:producto_new' %}"><i class="fa fa-calendar-plus"></i> Nueva</a>
        </div>
      </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">
        {% if not obj %}
            <div class="alert alert-info">No hay Productos</div>
        {% else %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Sub.Cat.</th>
                <th>Código</th>
                <th>Barra</th>
                <th>Descripcion</th>
                <th>Existencia</th>
                <th>Precio</th>
                <th>Marca</th>
                <th>U.M.</th>
                <th>Estado</th>
                <th class="all">Acciones</th>
            </thead>
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{item.subcategoria}}</td>
                        <td>{{item.codigo}}</td>
                        <td>{{item.codigo_barra}}</td>
                        <td>{{item.descripcion}}</td>
                        <td>{{item.existencia}}</td>
                        <td>{{item.precio}}</td>
                        <td>{{item.marca}}</td>
                        <td>{{item.unidad_medida}}</td>
                        <td>{{item.estado | yesno:"Activo,Inactivo"}}</td>
                        <td>
                            <a href="{% url 'inv:producto_edit' item.id %}" class="btn btn-warning btn-circle" role="button"><i class="far fa-edit"></i></a>
                            <a href="{% url 'inv:producto_inactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><i class="far fa-thumbs-down"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
  </div>
{% endblock %}

{% block js_page %}
<script>
 $(document).ready(function() {
    $('.table').DataTable({
      "language": {
        "sProcessing": "Procesando...",
        "sLengthMenu": "Mostrar _MENU_ registros",
        "sZeroRecords": "No se encontraron resultados",
        "sEmptyTable": "Ningún dato disponible en esta tabla",
        "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix": "",
        "sSearch": "Buscar:",
        "sUrl": "",
        "sInfoThousands": ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst": "<span class='fa fa-angle-double-left'></span>",
            "sLast": "<span class='fa fa-angle-double-right'></span>",
            "sNext": "<span class='fa fa-angle-right'></span>",
            "sPrevious": "<span class='fa fa-angle-left'></span>"
        },
        "oAria": {
            "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
      }
    });
  });
</script>
{% endblock %}